java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
java Reversi  randomcomputerplayer intelligentcomputerplayer | grep win >> wins.txt
